---
- hosts: all
  remote_user: vagrant
  sudo: yes
  tasks:
    - name: replace source.list
      copy: src=sources.list dest=/etc/apt/sources.list
    - name: install nodejs runtime
      apt: name={{ item }} update_cache=yes
      with_items:
        - nodejs
        - npm
    - name: install require npm packages
      npm: name=hexo global=yes registry=https://registry.npm.taobao.org
    - name: install packages based on package.json
      npm: path=/vagrant registry=https://registry.npm.taobao.org
