# Header
menu:
  主页: /
  归档: /archives
  关于: /about
rss: /atom.xml

sitemap:
    path: sitemap.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
widgets:
- tag

# Miscellaneous
google_analytics: UA-37439567-4
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
github: yunlzheng
weibo:
