# Header
menu:
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml

sitemap:
    path: sitemap.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
widgets:
- tag

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
github: yunlzheng
weibo:
