# Header
menu:
  文章: /
  Github:
    url: https://github.com/yunlzheng
    icon: github

# Title on top left of menu. Leave empty to use main blog title
menu_title: Peaceful

# URL of the Home page image
index_cover: http://7xj61w.com1.z0.glb.clouddn.com/header-bg-1.jpg

# Default post title
default_post_title: Untitled

copyright: true

# Comments. Choose one by filling up the information
comments:
  #
  uyan_id: 2137469
  # Disqus comments
  # disqus_shortname: shareks
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Addthis ID
addthis:

# set your own favicon
favicon:

# Social Accounts
twitter_url:
twitter_handle:
facebook_url:
github_url: https://github.com/yunlzheng
gitlab_url:
linkedin_url:
mailto:
